name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello and thank you for opening an issue for the first time! Be sure to read trough the template. And ask any questions if you need.'
        pr-message: 'Thank you so much for contributing to XVR! Be sure to read the template, if you have any questions feel free to ask.'
